# Generated by Django 4.1.7 on 2023-03-21 19:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import src.users.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specialists", models.PositiveSmallIntegerField()),
                ("clients", models.PositiveSmallIntegerField()),
                ("tours", models.PositiveSmallIntegerField()),
                ("years", models.PositiveSmallIntegerField()),
            ],
            options={
                "verbose_name": "About Us",
                "verbose_name_plural": "About Us",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                ("photo", models.ImageField(blank=True, upload_to="media/guides")),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Guide",
                "verbose_name_plural": "Guides",
            },
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    models.FileField(
                        upload_to=src.users.utils.path_and_rename,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "img", "jpg", "jpeg"]
                            )
                        ],
                    ),
                ),
                ("is_main", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(null=True, unique=True)),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "rating",
                    models.SmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5
                    ),
                ),
                ("date_published", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
            },
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("price", models.SmallIntegerField(verbose_name="Цена")),
                ("slug", models.SlugField(unique=True)),
                ("date_published", models.DateField(auto_now=True)),
                ("date_departure", models.DateField()),
                ("date_arrival", models.DateField()),
                ("quantity_limit", models.PositiveIntegerField()),
                (
                    "actual_limit",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                ("is_hot", models.BooleanField(default=False)),
                (
                    "duration",
                    models.CharField(
                        choices=[("1", "День"), ("3", "3 дня"), ("7", "7 дней")],
                        max_length=255,
                    ),
                ),
                (
                    "complexity",
                    models.CharField(
                        choices=[
                            ("Easy", "Легкий"),
                            ("Medium", "Средний"),
                            ("Hard", "Тяжелый"),
                            ("Extra", "Экстра"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "qr_code",
                    models.CharField(blank=True, default="", max_length=8, null=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tour.category",
                    ),
                ),
                (
                    "guide",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tour.guide",
                    ),
                ),
                (
                    "region",
                    models.ManyToManyField(
                        related_name="tour_region", to="tour.region"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tour",
                "verbose_name_plural": "Tours",
            },
        ),
    ]
