version: '3.3'

services:
  back:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic
        --no-input && gunicorn -b 0.0.0.0:8880 core.wsgi --reload"
    volumes:
      - ../:/home/app/web
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - db
    ports:
      -8000:8000
    
  db:
    image: postgres:latest
    container_name: ulul_db
    restart: unless-stopped
    ports:
      - "5535:5432"
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  nginx:
    image: nginx:1.13
    build: ./nginx
    container_name: ulul_nginx
    restart: unless-stopped
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - front:/home/app/front
    ports:
      - '89:80'
      - '449:443'
      - '8880:8880'
    depends_on:
      - ulul_backend
volumes:
  postgres_data:
  static_volume:
  media_volume:
  front:

