version: '3.3'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: ulul_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5447:5432'
  web:
    build: .
    container_name: ulul_web
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/home/app
      - ./static:/home/app/static
      - ./media:/home/app/media
    ports:
      - '8087:8087'
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: ulul_nginx
    restart: always
    ports:
      - '82:82'
      - '441:441'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - db

volumes:
  postgres_data: