version: '3.3'

services:
  ulul_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ulul_backend
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic
        --no-input && gunicorn -b 0.0.0.0:8880 core.wsgi --reload"
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: ulul_db
    restart: unless-stopped
    ports:
      - "5535:5432"
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  ulul_nginx:
    image: nginx:1.13
    build: ./nginx
    container_name: ulul_nginx
    restart: unless-stopped
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - front_media:/home/app/web/front_media
    ports:
      - '80:80'
      - '443:443'
      - '8443:8443'
    depends_on:
      - ulul_backend
volumes:
  postgres_data:
  static_volume:
  media_volume:
  front_media:

