version: '3.3'

services:
  back:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8880-8000
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic
        --no-input && gunicorn -b 0.0.0.0:8880 core.wsgi --reload"
    volumes:
      - .:/home/app/
      - ./ulul_dump.sql:/home/app/dump.sql
      - ./back_static:/home/app/back_static
      - ./back_media:/home/app/back_media
    networks:
      - nginx_network
      - db_network
     
  db:
    image: postgres:latest 
    restart: unless-stopped
    ports:
      - "5535:5432"
    volumes:
      - ./storage/data:/var/lib/postgresql/data
      
    env_file:
      - ./.env
    networks:
      - db_network

  nginx:
    image: nginx:1.13
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - ../Ulul-trip-front/build:/home/app/front/build
      - media_volume:/home/app/back_media
      - static_volume:/home/app/back_static
    ports:
      - '89:80'
      - '449:443'
    networks:
      - nginx_network
      - ulul-trip-front_front-network

volumes:
  static_volume:
  media_volume:

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge
  ulul-trip-front_front-network:
    external: true 
