version: '3.3'

services:
  db:
    image: postgres:latest
    container_name: ulultrip_db
    ports:
      - '5444:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - ./.env
  web:
    build: ./
    container_name: ulultrip_web
    command: sh -c 'python manage.py migrate && python manage.py collectstatic --no-input &&
      gunicorn -b 0.0.0.0:8000 config.wsgi --reload'
    restart: always
    ports:
      - '8888:8000'
    depends_on: 
      - db
    volumes:
      - '.:/app'
      - './static:/app/static'
      - './media:/app/media'
  nginx:
    build: ./nginx
    container_name: ulultrip_nginx
    restart: always
    ports:
      - '88:80'
    volumes:
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      - './static:/static'
      - './media:/media'
    depends_on:
      - web
volumes:
  postgres_data: