# Generated by Django 4.1.7 on 2023-03-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrderTour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Количество людей")),
                ("number", models.CharField(max_length=20, verbose_name="Номер")),
                (
                    "arranged_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата брони"),
                ),
                (
                    "way_of_payment",
                    models.CharField(max_length=20, verbose_name="Способ оплаты"),
                ),
                ("payment", models.ImageField(upload_to="media", verbose_name="Чек")),
            ],
        ),
    ]
