# Generated by Django 4.1.7 on 2023-03-21 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordertour",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_order",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
